global using Microsoft.EntityFrameworkCore;
global using VerticalSliceArchitectureTemplate.Common.Exceptions;
global using VerticalSliceArchitectureTemplate.Common.Features;
global using VerticalSliceArchitectureTemplate.Common.Persistence;
global using Immediate.Handlers.Shared;