<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Bogus" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\WebApi\WebApi.csproj" />
  </ItemGroup>
</Project>